### ISSUE TITLE
"Error: Invalid Login Auth Code"

### ISSUE THREAD

**Issue by GAMEBOOK** [Hawkite/steam-account-manager#2]
Hello

Thanks for this tool. I've open it add username/password and received and email.

If I send the code I have an error : Error: Invalid Login Auth Code

How can i fix ? Thanks

INFO : All working fine without SteamGuard but need use it.

**Comment by Hawkite** [comment]
Hello! Sorry, I will look into this for you. I've only tested it with the mobile authenticator. So if you are able to switch to that it should work fine.

Edit: Fixed! Sorry about that
